project:
  type: book
  output-dir: docs
  
book: 
  title: "EAD-ASEB-Ssolidissima-OA"
  
  page-footer: 
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>
      
      
  repo-url: https://github.com/Emily-A-Roberts/EAD-ASEB-Ssolidissima-OA
  repo-branch: main
  chapters: 
    - index.qmd
    - projects/Biodeposition/scripts/Biodeposition_summary.qmd
    - projects/Biodeposition/scripts/Pousse_Meseck_Size_scaling.qmd
    #- part: intertidal_experiment_model.qmd
    #  chapters: 
    #    - intertidal_environmental_data.qmd
     #   - intertidal_growth_data.qmd
     #   - intertidal_model_optimization.qmd
   # - additional_figures.qmd
   # - sensitivity_analysis.qmd
   # - climate_change_predictions.qmd
    
format:
  html: 
    theme: 
      - cosmo
    
editor: visual


execute:
  freeze: auto    
    



