---
title: "pH_HOBO_plots 1.1"
author: "Emily Roberts"
#format: html
format: 
  pdf:
    toc: TRUE
    number-sections: TRUE
    colorlinks: TRUE
editor: visual

date: 2023-12-17
date-format: short
abstract: "Trim individual files to time deployed and retrieved, then compile and visualize the data. "
---

## Set up workspace

```{r}
#| include: FALSE
library(ggplot2)
library(ggpubr)
library(dplyr)
library(lubridate)


data_combined_new <- data.frame(
  Site = NA,
  Date = NA,
  Temp = NA,
  pH = NA
)

# working directories
wdDen <- "~/GitHub/EAD-ASEB-Ssolidissima-OA/projects/Seawater data/data/HOBOpHdata/Dennis"
wdPtown <- "~/GitHub/EAD-ASEB-Ssolidissima-OA/projects/Seawater data/data/HOBOpHdata/Ptown"
wdEel <- "~/GitHub/EAD-ASEB-Ssolidissima-OA/projects/Seawater data/data/HOBOpHdata/Eel_Pond"
```

### Dennis

```{r}
setwd(wdDen)
filenames <- dir()
filenames
```

```{r}
setwd(wdDen)
# Late June to early Aug
#(open_file <- filenames[1]) # "1230_East_Dennis 2022-08-05 16_12_44 EDT (Data EDT).csv"
open_file <- "1230_East_Dennis 2022-08-05 16_12_44 EDT (Data EDT).csv"
#Also works: (open_file <- filenames[2]) # "1230_East_Dennis 2022-09-21 09_29_48 EDT (Data EDT).csv"
df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime<"2022-08-04 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Den",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined_new)
```

```{r}
setwd(wdDen)
# Late June to early Aug
#(open_file <- filenames[1]) # "1230_East_Dennis 2022-08-05 16_12_44 EDT (Data EDT).csv"
open_file <- "1230_East_Dennis 2022-08-05 16_12_44 EDT (Data EDT).csv"
#Also works: (open_file <- filenames[2]) # "1230_East_Dennis 2022-09-21 09_29_48 EDT (Data EDT).csv"
df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime<"2022-08-04 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Den",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined_new)

```

```{r}
setwd(wdDen)
# Aug to mid September
#"Den_077 2022-09-14 14_08_26 EDT (Data EDT).csv" 
#"Den_077 2022-09-21 09_28_37 EDT (Data EDT)(1).csv" is the same file read out later on
#(open_file <- filenames[3])
open_file <- "Den_077 2022-09-14 14_08_26 EDT (Data EDT).csv" 
df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2022-08-05 00:00:00 EDT",]
df <- df[df$datetime<"2022-09-13 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Den",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)

head(data_combined_new)
tail(data_combined_new)

```

### Ptown

```{r}
setwd(wdPtown)
filenames <- dir()
filenames
```

```{r}
setwd(wdPtown)
# mid June to August
open_file <- "20573560_Ptown 2022-08-05 17_08_58 EDT (Data EDT).csv"
df <- read.csv(open_file, stringsAsFactors = F)
head(df)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime<"2022-08-03 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Ptown",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)

```

```{r}
setwd(wdPtown)
# August
(open_file <- filenames[6])
open_file <- "Ptown_075 2022-08-29 21_52_54 EDT (Data EDT).csv"
df <- read.csv(open_file, stringsAsFactors = F)
head(df)
tail(df)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2022-08-04 00:00:00 EDT",]
df <- df[df$datetime<"2022-08-29 00:00:00 EDT",]
#plot(df$datetime, df$Ch..3...pH....pH., type = "l")
#plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
#plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Ptown",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)

```

SN560 8/28/22

Tris 8.20pH, 24.73C

```{r}
setwd(wdPtown)
# September
# Also is here: "20573560_Ptown 2022-11-02 15_02_10 EDT (Data EDT).csv"
open_file <- "Ptown_20573560_Ptown 2022-09-29 17_27_52 EDT (Data EDT).csv"
df <- read.csv(open_file, stringsAsFactors = F)
head(df)
tail(df)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2022-08-30 00:00:00 EDT",]
df <- df[df$datetime<"2022-09-26 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Ptown",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)

```

```{r}
setwd(wdPtown)
# early October
# This sensor seems to be deployed at Eel pond originally, recalibrated without a change in the name, 
# and then moved to Ptown. The segment at Ptown starts late in the day on 9/27/22
filenames
open_file <- "21333340_Eel_Pond 2022-11-07 15_11_16 EST (Data EST)_actuallyPtown.csv"
df <- read.csv(open_file, stringsAsFactors = F)
head(df)
tail(df,80)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EST., format = "%m/%d/%Y %H:%M:%S")) #Switch to EST????
plot(df$datetime, df$Ch..3...pH....pH.)
# df <- df[df$datetime>"2022-09-25 00:00:00 EDT",]
# df <- df[df$datetime<"2022-09-29 13:00:00 EDT",]
df <- df[df$datetime>"2022-09-28 00:00:00 EDT",]
df <- df[df$datetime<"2022-11-07 13:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "p")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Ptown",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)

```

```{r}
setwd(wdPtown)
# November
# However this last file seems a bit out of place. Could be Eel Pond. 
# Yes this is Provincetown. It is collected on 12/4 not 12/5, which makes way more sense. 
# It is deployed by 11/7/23 15:30,which is later than our Ptown date. I could have gone out and done this on Sunday morning if I wasn't able to get out there on 11/4/23. I would have then pulled SN340 on the same date. 
# Ah yes I did a one day trip where I met Matt to pick up the sensor and deployed it. It must have previously been deployed in Eel Pond.

open_file <- "Ptown_076 2022-12-05 21_20_00 EST (Data EST).csv"
df <- read.csv(open_file, stringsAsFactors = F)
head(df)
tail(df,80)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EST., format = "%m/%d/%Y %H:%M:%S")) #Switch to EST????
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2022-11-07 13:00:00 EDT",]#"2022-11-07 13:00:00 EDT"
df <- df[df$datetime<"2022-12-04 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Ptown",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)

```

```{r}
setwd(wdPtown)
# skip to April to avoid freezing temps

open_file <- "20573560_Ptown 2023-05-10 14_13_07 EDT (Data EDT).csv"
df <- read.csv(open_file, stringsAsFactors = F)
head(df)
tail(df,80)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%y %H:%M")) #Switch to EDT from EST?
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2023-04-18 15:15:15",]
df <- df[df$datetime<"2023-05-10 09:00:00",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C., type = "l")
length(df$Ch..1...Temperature.....C.)

plot(df$Ch..1...Temperature.....C., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Ptown",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C.,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)
```

```{r}

setwd(wdPtown)
# skip to April to avoid freezing temps

open_file <- "340_Ptown 2023-06-11 14_35_41 EDT (Data EDT)(1).csv" 
df <- read.csv(open_file, stringsAsFactors = F)
head(df)
tail(df,80)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M")) #Switch to EDT from EST?
plot(df$datetime, df$Ch.3...pH....pH.)
df <- df[df$datetime>"2023-05-10 09:45:00",]
df <- df[df$datetime<"2023-06-11 11:45:00",]
plot(df$datetime, df$Ch.3...pH....pH., type = "l")
plot(df$datetime, df$Ch.1...Temperature.....C., type = "l")
length(df$Ch..1...Temperature.....C.)

plot(df$Ch.1...Temperature.....C., df$Ch.3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Ptown",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch.1...Temperature.....C.,
  pH = df$Ch.3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)
```

### Eel Pond

```{r}
setwd(wdEel)
filenames <- dir()
filenames
```

```{r}
setwd(wdEel)
#mid June to Aug
#(open_file <- filenames[2])
(open_file <- "21333340_Eel_Pond 2022-08-05 17_43_02 EDT (Data EDT).csv")
df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime<"2022-08-01 00:00:00 EDT",]
df <- df[df$datetime>"2022-06-17 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Eel",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)
# Aug to lateAug is on logger that is still logging in Eel Pond and 
# needs to be retrieved.
# There was an issue with the tool when swapping them out

```

```{r}
setwd(wdEel)
#Aug to lateAug
(open_file <- filenames[4])
(open_file <- "Eel_076 2022-09-27 13_35_57 EDT (Data EDT).csv")
df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime<"2022-08-30 00:00:00 EDT",]
df <- df[df$datetime>"2022-08-02 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Eel",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)
# Aug to lateAug is on logger that is still logging in Eel Pond and 
# needs to be retrieved.
# There was an issue with the tool when swapping them out


# # lateAug to mid Sep (was still logging and deployed - 
# # but lost ~14 days of data due to calibrating before downloading data)
# (open_file <- filenames[3])
# open_file <- "21333340_Eel_Pond 2022-09-11 18_27_18 EDT (Data EDT).csv"
# 
# df <- read.csv(open_file, stringsAsFactors = F)
# df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S"))
# plot(df$datetime, df$Ch..3...pH....pH.)
# df <- df[df$datetime>"2022-08-31 00:00:00 EDT",]
# df <- df[df$datetime<"2022-09-11 00:00:00 EDT",]
# plot(df$datetime, df$Ch..3...pH....pH., type = "l")
# plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
# plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')
# 
# data_combined_new <- data.frame(
#   Site = rep("Eel",times = nrow(df)),
#   Date = df$datetime,
#   Temp = df$Ch..1...Temperature.....C..,
#   pH = df$Ch..3...pH....pH.
# )
# 
# 
# data_combined <- rbind(data_combined,data_combined_new)

```

```{r}
setwd(wdEel)
# #October???
# #October is not clear.
# #If the other legger was still logging and deployed at this site
# (open_file <- filenames[3])
# open_file <- "Eel_076 2022-11-07 15_16_01 EST (Data EST)(1).csv"
# head(df, 20)
# df <- read.csv(open_file, stringsAsFactors = F)
# df$datetime <- as.POSIXct(strptime(df$Date.Time..EST., format = "%m/%d/%Y %H:%M:%S")) #Change to EST
# plot(df$datetime, df$Ch..3...pH....pH.)
#  df <- df[df$datetime>"2022-09-25 00:00:00 EDT",]
# # df <- df[df$datetime<"2022-09-30 00:00:00 EDT",]
# 
# #df <- df[df$datetime<"2022-08-31 00:00:00 EDT",]
# #df <- df[df$datetime>"2022-08-26 00:00:00 EDT",]
# plot(df$datetime, df$Ch..3...pH....pH., type = "l")
# plot(df$datetime, df$Ch..1...Temperature.....C.., type = "p")
# plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')
# 
# data_combined_new <- data.frame(
#   Site = rep("Eel",times = nrow(df)),
#   Date = df$datetime,
#   Temp = df$Ch..1...Temperature.....C..,
#   pH = df$Ch..3...pH....pH.
# )
# 
# 
# data_combined <- rbind(data_combined,data_combined_new)

# October
# This sensor seems to be deployed at Eel pond originally, recalibrated without a change in the name, 
# and then moved to Ptown. The segment at Eel Pond ends on Monday 9/26/22.
# It was deployed on 8/31/22. Which is a day we were at Eel Pond
filenames
open_file <- "21333340_Eel_Pond 2022-11-07 15_11_16 EST (Data EST)_actuallyPtown.csv"
df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EST., format = "%m/%d/%Y %H:%M:%S")) #Switch to EST????
plot(df$datetime, df$Ch..3...pH....pH.)
# df <- df[df$datetime>"2022-09-25 00:00:00 EDT",]
# df <- df[df$datetime<"2022-09-29 13:00:00 EDT",]
df <- df[df$datetime>"2022-08-31 00:00:00 EDT",]
df <- df[df$datetime<"2022-09-26 13:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "p")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Eel",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)

data_combined <- rbind(data_combined,data_combined_new)




```

```{r}
setwd(wdEel)
# October
#(open_file <- filenames[3])
open_file <- "Eel_076 2022-11-07 15_16_01 EST (Data EST)(1).csv"
head(df, 20)
df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EST., format = "%m/%d/%Y %H:%M:%S")) #Change to EST
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2022-09-29 00:00:00 EDT",]
df <- df[df$datetime<"2022-11-06 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Eel",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)


data_combined <- rbind(data_combined,data_combined_new)
```

```{r}
setwd(wdEel)
# November
#(open_file <- filenames[3])
open_file <- "20573560_Ptown 2022-12-05 16_55_15 EST (Data EST)_actuallyEel.csv"

df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EST., format = "%m/%d/%Y %H:%M:%S")) #Change to EST
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2022-11-07 00:00:00 EDT",]
df <- df[df$datetime<"2022-12-05 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C.., type = "l")
plot(df$Ch..1...Temperature.....C.., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Eel",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C..,
  pH = df$Ch..3...pH....pH.
)


data_combined <- rbind(data_combined,data_combined_new)


```

```{r}
setwd(wdEel)
# May
#(open_file <- filenames[3])
open_file <- "21333340_Eel_Pond 2023-05-08 09_10_54 EDT (Data EDT).csv"

df <- read.csv(open_file, stringsAsFactors = F)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S")) #Change to EST
plot(df$datetime, df$Ch..3...pH....pH.)
df <- df[df$datetime>"2023-04-19 17:00:00 EDT",]
#df <- df[df$datetime<"2022-12-05 00:00:00 EDT",]
plot(df$datetime, df$Ch..3...pH....pH., type = "l")
plot(df$datetime, df$Ch..1...Temperature.....C., type = "l")
plot(df$Ch..1...Temperature.....C., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Eel",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch..1...Temperature.....C.,
  pH = df$Ch..3...pH....pH.
)


data_combined <- rbind(data_combined,data_combined_new)
```

```{r}
setwd(wdEel)
# June
#(open_file <- filenames[3])
open_file <- "Eel_076 2023-06-11 14_39_04 EDT (Data EDT).csv"

df <- read.csv(open_file, stringsAsFactors = F)
tail(df)
df$datetime <- as.POSIXct(strptime(df$Date.Time..EDT., format = "%m/%d/%Y %H:%M:%S")) #EDT
plot(df$datetime, df$Ch.3...pH....pH.)
df <- df[df$datetime>"2023-05-08 07:30:00 EDT",]
df <- df[df$datetime<"2023-06-09 10:45:00 EDT",]
plot(df$datetime, df$Ch.3...pH....pH, type = "l")
plot(df$datetime, df$Ch.1...Temperature.....C., type = "l")
plot(df$Ch.1...Temperature.....C., df$Ch..3...pH....pH., pch = '.')

data_combined_new <- data.frame(
  Site = rep("Eel",times = nrow(df)),
  Date = df$datetime,
  Temp = df$Ch.1...Temperature.....C.,
  pH = df$Ch.3...pH....pH.
)


data_combined <- rbind(data_combined,data_combined_new)
```

## Combine

```{r}
setwd("~/GitHub/EAD-ASEB-Ssolidissima-OA/projects/Seawater data/data/HOBOpHdata")

write.csv(data_combined, file = "pH data combined.csv")
# rm(list = ls())
# data_combined <- read.csv("pH data combined.csv", stringsAsFactors = FALSE)

g1 <- ggplot(data_combined, aes(x=Date, y=pH, colour = Site))+
  geom_point(cex = .1) +
  scale_color_manual(values=c("blue", "green", "orange"))
g1

g2 <- ggplot(data_combined, aes(x=Date, y=Temp, colour = Site))+
  geom_point(cex = .1) +
  scale_color_manual(values=c("blue", "green", "orange"))

ggarrange(g1, g2)

min(data_combined$Date)

```

### Plot tides

```{r}
# Plot tides
setwd("~/GitHub/EAD-ASEB-Ssolidissima-OA/projects/Seawater data/data/Tides")
dir()
tides.Ptown1 <- read.table("Ptown_Jul.txt", skip =14)
tides.Ptown2 <- read.table("Ptown_Aug.txt", skip =14)
tides.Ptown3 <- read.table("Ptown_Sep.txt", skip =14)
tides.Ptown4 <- read.table("Ptown_Oct.txt", skip =14)
tides.Ptown5 <- read.table("Ptown_Nov.txt", skip =14)
tides.Ptown6 <- read.table("Ptown_Dec.txt", skip =14)
tides.Ptown7 <- read.table("Ptown_Apr23.txt", skip =14)
tides.Ptown8 <- read.table("Ptown_May23.txt", skip =14)
tides.Ptown9 <- read.table("Ptown_Jun23.txt", skip =14)
tides.Den1 <- read.table("Den_Jul.txt", skip =14)
tides.Den2 <- read.table("Den_Aug.txt", skip =14)
tides.Den3 <- read.table("Den_Sep.txt", skip =14)
tides.Eel1 <- read.table("Hyannis_Jul.txt", skip =14)
tides.Eel2 <- read.table("Hyannis_Aug.txt", skip =14)
tides.Eel3 <- read.table("Hyannis_Sep.txt", skip =14)
tides.Eel4 <- read.table("Hyannis_Oct.txt", skip =14)
tides.Eel5 <- read.table("Hyannis_Nov.txt", skip =14)
tides.Eel6 <- read.table("Hyannis_Dec.txt", skip =14)
tides.Eel7 <- read.table("Hyannis_Apr23.txt", skip =14)
tides.Eel8 <- read.table("Hyannis_May23.txt", skip =14)
tides.Eel9 <- read.table("Hyannis_Jun23.txt", skip =14)

tides.Ptown <- rbind(tides.Ptown1, tides.Ptown2, tides.Ptown3,
                     tides.Ptown4, tides.Ptown5, tides.Ptown6,
                     tides.Ptown7, tides.Ptown8, tides.Ptown9)
tides.Den <- rbind(tides.Den1, tides.Den2, tides.Den3)
tides.Eel <- rbind(tides.Eel1, tides.Eel2, tides.Eel3,
                   tides.Eel4, tides.Eel5, tides.Eel6,
                   tides.Eel7, tides.Eel8, tides.Eel9)

tides <- data.frame(tides = rbind(tides.Ptown,tides.Den,tides.Eel),
           Site = as.factor(c(rep("Ptown",times=nrow(tides.Ptown)),
                     rep("Den",times=nrow(tides.Den)),
                     rep("Eel",times=nrow(tides.Eel)))))
names(tides)<- c("date","day","Time","Tideheight","Site")

Date1 <- paste(tides$date,tides$Time,sep=" ")

tides$Date <- as.POSIXct(strptime(Date1,format = "%Y/%m/%d %H:%M"),tz="Etc/GMT+5")

tides$Date[tides$Site=="Eel"] <- tides$Date[tides$Site=="Eel"]+ minutes(60) #Eel Pond tide is delayed by about half an hour consistantely compared to the local tide stations. 

data_combined$Date<-as.POSIXct(data_combined$Date, tz="Etc/GMT+5")
data_combined$Date<-round_date(data_combined$Date, unit="minutes")

data_combined$Site<-as.factor(data_combined$Site)
data_combined$H_plus_conc<-10^(-data_combined$pH)

joined_df <- left_join(x=data_combined, y=tides, by= c("Date","Site"))
```

```{r}
# Plot tides --------------------------------------------------------------
Ptown <- joined_df[joined_df$Site=="Ptown",]
plot(Temp~Tideheight, pch =".",type ="b", data = Ptown, main="Ptown")
plot(pH~Tideheight,pch=".",data = Ptown, type = "b", main="Ptown")
lines(x=c(.4,.4),y=c(5,9),lwd=3)
# This graph seems to demonstrate that pH goes up or down at low tide (I'm guessing night or day) 
# but below a certain point goes to ~7.8 - I think this is when the pH probe is not 
# in water anymore.

Den <- joined_df[joined_df$Site=="Den",]
plot(Temp~Tideheight, pch =".",type ="l", data = Den, main="Den")
plot(Tideheight~Temp, pch =".",type ="l", data = Den, ylim = c(-2,2),main="Den")
# What concerns me are the lines where temp rapidly increases at low tide. I expect some slow temp increase, but not rapid. 
# I also wonder about introducing a lag of a few hours after the sensor has been out of the water. Not here, but in the future. 

plot(pH~Tideheight,pch=".",data = Den, type = "b", main="Den")
lines(x=c(.5,.5),y=c(5,9),lwd=3) 


Eel <- joined_df[joined_df$Site=="Eel",]
plot(Temp~Tideheight, pch =".",type ="l", data = Eel, main="Eel")
plot(pH~Tideheight,pch=".",data = Eel, type = "l", main="Eel")
lines(x=c(0,0),y=c(5,30),lwd=3) 
plot(pH~Temp,  pch =".",type ="b", data = Eel, main="Eel")
# Not clear from data what tide is too low. It might be more wind-dependent. 
# At 0.5ft tide the cages are on sediment that is about 2.5 ft deep. 
# The sensor is installed <0.5ft above the sediment. However there is likely a mismatch between tide data at this site and 
# The actual water level - the site water level does not vary much.
# Honestly, I don't see anything in this data linked with the tides to suggest that I'm getting bad data when the tides go out.
# If anything, the highest temps occur when the low tides are really minimal.
# The HOBO temp logger will probably help the most in figuring this out, 
# it will help determine if there is some wind/tide-driven bad data or not due to sensor exposure. 

```

Exclude pH from times water below low tide mark.

```{r}
Ptown <- Ptown[Ptown$Tideheight>1,] #This was at 0.4
Den <- Den[Den$Tideheight>2,] #This was at .5
Eel <- Eel[Eel$Tideheight>1,] #This was at 0. 
```

```{r}
# Aggregate data --------------------------------------------------------------

Ptown.hr <- aggregate(Ptown[,c("pH","Temp","H_plus_conc")], 
                         list(Date = cut(Ptown[,c("Date")], breaks="hour")), 
                         mean, na.rm = TRUE)
Den.hr <- aggregate(Den[,c("pH","Temp","H_plus_conc")], 
                      list(Date = cut(Den[,c("Date")], breaks="hour")), 
                      mean, na.rm = TRUE)
Eel.hr <- aggregate(Eel[,c("pH","Temp","H_plus_conc")], 
                      list(Date = cut(Eel[,c("Date")], breaks="hour")), 
                      mean, na.rm = TRUE)

all.data.hr <- data.frame(
  rbind(Ptown.hr,Den.hr,Eel.hr),
  Site = as.factor(c(rep("Ptown",times = nrow(Ptown.hr)),
           rep("Den",times = nrow(Den.hr)),
           rep("Eel",times = nrow(Eel.hr))))
           )
all.data.hr$Date<- as.POSIXct(all.data.hr$Date)

all.data.hr.break <- all.data.hr[1:3,]
all.data.hr.break$Date <- "2023-01-01 00:00:00"
all.data.hr.break$pH <- NA
all.data.hr.break$Temp <- NA
all.data.hr.break$Site <- c("Ptown", "Eel", "Den")
all.data.hr <- rbind(all.data.hr,all.data.hr.break)

head(all.data.hr)

```

```{r}

Ptown.wk <- aggregate(Ptown[,c("pH","Temp","H_plus_conc")], 
                         list(Date = cut(Ptown[,c("Date")], breaks="week")), 
                         mean, na.rm = TRUE)
Den.wk <- aggregate(Den[,c("pH","Temp","H_plus_conc")], 
                      list(Date = cut(Den[,c("Date")], breaks="week")), 
                      mean, na.rm = TRUE)
Eel.wk <- aggregate(Eel[,c("pH","Temp","H_plus_conc")], 
                      list(Date = cut(Eel[,c("Date")], breaks="week")), 
                      mean, na.rm = TRUE)

all.data.wk <- data.frame(
  rbind(Ptown.wk,Den.wk,Eel.wk),
  Site = as.factor(c(rep("Ptown",times = nrow(Ptown.wk)),
           rep("Den",times = nrow(Den.wk)),
           rep("Eel",times = nrow(Eel.wk))))
           )
all.data.wk$Date<- as.POSIXct(all.data.wk$Date)
head(all.data.wk)

all.data.wk.break <- all.data.wk[1:3,]
all.data.wk.break$Date <- "2023-01-01 00:00:00"
all.data.wk.break$pH <- NA
all.data.wk.break$Temp <- NA
all.data.wk.break$Site <- c("Ptown", "Eel", "Den")
all.data.wk <- rbind(all.data.wk,all.data.wk.break)
tail(all.data.wk)


```

Technically pH should be averaged on the log scale because it is the log of a concentration. The arithmetic average will be slightly different from the true average.

```{r}
all.data.wk$pH <- -log10(all.data.wk$H_plus_conc) 
all.data.hr$pH <- -log10(all.data.hr$H_plus_conc)
```

### Final plots

```{r}
# plot(all.data$Date, all.data$pH, 
#      color = as.factor(data_combined$Site), pch = ".")

sampling.pH <- data.frame(
  x = as.POSIXct(c("2022-06-29 00:00:00 EDT","2022-08-2 00:00:00 EDT","2022-09-9 00:00:00 EDT","2022-12-01 00:00:00 EDT","2023-04-01 00:00:00 EDT","2023-06-1 00:00:00 EDT")),
  y = c(7.5,7.5,7.5,7.5,7.5,7.5)
)
sampling.temp <- data.frame(
  x = as.POSIXct(c("2022-06-29 00:00:00 EDT","2022-08-2 00:00:00 EDT","2022-09-9 00:00:00 EDT","2022-12-01 00:00:00 EDT","2023-04-01 00:00:00 EDT","2023-06-1 00:00:00 EDT")),
  y = c(5,5,5,5,5,5)
)

theme_set(theme_bw())

colors <- c(
  "Den"="blue",
  "Eel"="green",
  "Ptown"="orange",
  "Date sampled"="black"
)

#scale_color_manual(values=c("blue", "green", "orange"))

# Now I'm aggregating by day... and this is a bit easier to digest when comparing among sites
head(all.data.wk)
str(all.data.wk)

gg1 <- ggplot(all.data.wk, aes(x=Date, y=pH, colour = Site))+
  geom_point(cex = 1) +
  geom_line(cex = 1)+
  ylim(7.5,8.3)+
  #xlim(as.POSIXct(c("2022-06-29 00:00:00 EDT","2022-09-9 00:00:00 EDT")))+
  geom_point(data = sampling.pH, aes(x,y), color = "black", cex = 5)+
  scale_color_manual(values=colors) +
  guides(colour = guide_legend(override.aes = list(size=5)))+
  ggtitle('B. pH')


ylab = expression("Temperature " ( degree*C))

gg2 <- ggplot(all.data.wk, aes(x=Date, y=Temp, colour = Site))+
  geom_point(cex = 1) +
  geom_line(cex = 1)+
  labs(y=ylab)+
  #ylim(14,30)+
  #xlim(as.POSIXct(c("2022-06-29 00:00:00 EDT","2022-09-9 00:00:00 EDT")))+
  geom_point(data = sampling.temp, aes(x,y), color = "black", cex = 5)+
  scale_color_manual(values=colors) +
  guides(colour = guide_legend(override.aes = list(size=5)))+
  ggtitle('A. Temp')



ggarrange(gg2, gg1, common.legend = TRUE, legend="bottom")

#
```

```{r}
setwd("~/GitHub/EAD-ASEB-Ssolidissima-OA/projects/Seawater data/data/HOBOpHdata")
write.csv(all.data.wk, file="Summary_weekly_ave.csv")
write.csv(all.data.hr, file="Summary_hourly_ave.csv")
```

```{r}
# Subset data - playing around --------------------------------------------------------------

# all.data <- joined_df[joined_df$Site=="Ptown"&joined_df$Tideheight>2|
#                         joined_df$Site=="Den"&joined_df$Tideheight>2|
#                         joined_df$Site=="Eel"&joined_df$Tideheight>2,]
# 
# # Plot        --------------------------------------------------------------
# 
# plot(all.data$Date, all.data$pH, 
#      color = as.factor(data_combined$Site), pch = ".")
# 
# g1 <- ggplot(all.data, aes(x=Date, y=pH, colour = Site))+
#   geom_point(cex = .1) +
#   scale_color_manual(values=c("blue", "green", "orange"))
# 
# g2 <- ggplot(all.data, aes(x=Date, y=Temp, colour = Site))+
#   geom_point(cex = .1) +
#   scale_color_manual(values=c("blue", "green", "orange"))
# 
# ggarrange(g1, g2)
# 
# 
# 
# min(data_combined$Date)

```

```{r}
# I need to add all of the tide data so I can subset the data using tide data


# Tide data websites:
#https://tidesandcurrents.noaa.gov/map/index.html
# Dennis https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8447241&units=standard&bdate=20220901&edate=20220930&timezone=LST/LDT&clock=24hour&datum=MLLW&interval=1&action=dailychart
# Falmouth - only L/H: https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8447865
# Hyannis - https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=8447605
# Note I'm using the Hyannis dataset because they have down to 1min predictions. Falmouth does not.
# Compared to Eel Pond Entrance on Willy Weather, Hyannis is ~30 min behind - which is perfect. The tide in Eel pond seems to be ~1/2 hour after 
# Willy Weather says it is. 
```
